on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get application code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build Docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t microvisor-app-test-image .
    - name: Build application code
      run: docker run --rm -v $(pwd)/:/home/mvisor/project/ --name microvisor-app-test-demo microvisor-app-test-image
    - name: Upload bundle
      uses: actions/upload-artifact@v3
      with:
        name: mv-app-test-stub-bundle
        path: ${{ github.workspace }}/build/app/mv-app-test.zip